# Database
POSTGRESQL_HOST: localhost
POSTGRESQL_PORT: 5432
POSTGRESQL_NAME: bio_db
POSTGRESQL_USERNAME: postgres
POSTGRESQL_PASSWORD: maria17

# Server Config
CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

# Web Config
UI_APP_URL: http://localhost:5173
