# Database
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_DB: bio_db
POSTGRES_USER: postgres
POSTGRES_PASSWORD: maria17

# Server Config
CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

# Web Config
UI_APP_URL: http://localhost:5173

JWT_SECRET: josmaria17cuentas?
