server:
  port: ${CONTAINER_PORT:8080}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

ui:
  app:
    url: ${UI_APP_URL}
