spring:
  application:
    name: bio
  datasource:
    url: jdbc:postgresql://localhost:5432/bio_db
    username: postgres
    password: maria17
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
